Conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace= 'users')),
    path('blogs/',include('blogs.urls',namespace='blogs')),
    path('',include('pages.urls',namespace='pages')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('contact/',views.contact_page_views,name='contact'),
    path('about/',views.about_page_views,name='about'),
    path('',views.home_page_views,name='home'),
]

templates/pages/about.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<!-- Inne Page Banner Area Start Here -->
    <section class="inner-page-banner bg-common" data-bg-image="{% static 'img/figure/inner-page-banner1.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-area">
                        <h1>About Us</h1>
                        <ul>
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>About</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Inne Page Banner Area End Here -->
    {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Hey! </strong>{{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <!-- Recipe With Sidebar Area Start Here -->
    <section class="all-recipes-page-wrap padding-top-80 padding-bottom-50">
    <div class="container">
        <div class="row gutters-60">
            <div class="col-lg-8">
                <div class="about-box">
                    <div class="about-figure">
                        <img src="{% static 'img/figure/about2.jpg' %}" alt="About">
                    </div>
                    <h2 class="about-title title-bar bar-center">Rosario Kareon</h2>
                    <p class="item-description">More off this less hello salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Google Recipe View. Schema.org is a collaboration byo improve the web by creatinegaera structured data markupore off this less hello salamander lied 
                            porpoise much over tightlyapedey innocuouslylife.</p>
                    <div class="section-heading heading-dark">
                        <h2 class="item-heading">QUICK CONTACT ME</h2>
                    </div>
                    <form class="about-contact-form" method="post" action="{% url 'pages:about' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4 form-group">
                                <input type="text" placeholder="Name *" class="form-control" name="name" data-error="Name field is required"
                                    required>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-md-4 form-group">
                                <input type="email" placeholder="E-mail *" class="form-control" name="email" data-error="E-mail field is required"
                                    required>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-md-4 form-group">
                                <input type="text" placeholder="Phone *" class="form-control" name="phone"
                                    data-error="Subject field is required" required>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-12 form-group">
                                <textarea placeholder="Message" class="textarea form-control" name="message" id="form-message"
                                    rows="7" cols="20" data-error="Message field is required" required></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="col-12 form-group mb-0 mt-3">
                                <button type="submit" class="item-btn">SEND MESSAGE</button>
                            </div>
                            <div class="form-response"></div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-4 sidebar-widget-area sidebar-break-md">
                <div class="widget">
                    <div class="section-heading heading-dark">
                        <h3 class="item-heading">SUBSCRIBE &amp; FOLLOW</h3>
                    </div>
                    <div class="widget-follow-us">
                        <ul>
                            <li class="single-item"><a href="#"><i class="fab fa-facebook-f"></i>LIKE ME ON</a></li>
                            <li class="single-item"><a href="#"><i class="fab fa-twitter"></i>LIKE ME</a></li>
                            <li class="single-item"><a href="#"><i class="fab fa-linkedin-in"></i>LIKE ME</a></li>
                            <li class="single-item"><a href="#"><i class="fab fa-pinterest-p"></i>LIKE ME</a></li>
                            <li class="single-item"><a href="#"><i class="fab fa-instagram"></i>LIKE ME</a></li>
                            <li class="single-item"><a href="#"><i class="fab fa-youtube"></i>Subscribe</a></li>
                        </ul>
                    </div>
                </div>
                <div class="widget">
                    <div class="section-heading heading-dark">
                        <h3 class="item-heading">LATEST RECIPES</h3>
                    </div>
                    <div class="widget-latest">
                        <ul class="block-list">
                            <li class="single-item">
                                <div class="item-img">
                                    <a href="#"><img src="{% static 'img/product/latest1.jpg' %}" alt="Post"></a>
                                    <div class="count-number">1</div>
                                </div>
                                <div class="item-content">
                                    <div class="item-ctg">DESERT</div>
                                    <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                            Mozzarella Oelette</a></h4>
                                    <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                            John Martin</a></div>
                                </div>
                            </li>
                            <li class="single-item">
                                <div class="item-img">
                                    <a href="#"><img src="{% static 'img/product/latest2.jpg' %}" alt="Post"></a>
                                    <div class="count-number">2</div>
                                </div>
                                <div class="item-content">
                                    <div class="item-ctg">DESERT</div>
                                    <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                            Mozzarella Oelette</a></h4>
                                    <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                            John Martin</a></div>
                                </div>
                            </li>
                            <li class="single-item">
                                <div class="item-img">
                                    <a href="#"><img src="{% static 'img/product/latest3.jpg' %}" alt="Post"></a>
                                    <div class="count-number">3</div>
                                </div>
                                <div class="item-content">
                                    <div class="item-ctg">DESERT</div>
                                    <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                            Mozzarella Oelette</a></h4>
                                    <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                            John Martin</a></div>
                                </div>
                            </li>
                            <li class="single-item">
                                <div class="item-img">
                                    <a href="#"><img src="{% static 'img/product/latest4.jpg' %}" alt="Post"></a>
                                    <div class="count-number">4</div>
                                </div>
                                <div class="item-content">
                                    <div class="item-ctg">DESERT</div>
                                    <h4 class="item-title"><a href="#">Salami Oven Roasted are
                                            Mozzarella Oelette</a></h4>
                                    <div class="item-post-by"><a href="single-blog.html"><i class="fas fa-user"></i><span>by</span>
                                            John Martin</a></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="widget">
                    <div class="widget-ad">
                        <a href="#"><img src="{% static 'img/figure/figure4.jpg' %}" alt="Ad" class="img-fluid"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
<!-- Recipe With Sidebar Area End Here -->
{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <!-- Inne Page Banner Area Start Here -->
    <section class="inner-page-banner bg-common" data-bg-image="{% static 'img/figure/inner-page-banner1.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-area">
                        <h1>Contact With Us</h1>
                        <ul>
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>Contact</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Inne Page Banner Area End Here -->
    {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Hey! </strong>{{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <!-- Contact Page Area Start Here -->
    <section class="contact-page-wrap">
        <div class="contact-box-left">
            <div class="container">
                <div class="section-heading heading-dark">
                    <h3 class="item-heading-big">Our Address</h3>
                </div>
                <p>Korem ipsum dolor sitter amet consectetuer adipiscing elitter Curabt
                    ur ugueque habitant morbi tristique.</p>
                <div class="contact-address">
                    <ul>
                        <li>
                            <div class="item-icon"><i class="fas fa-map"></i></div>
                            House #111/B, Street #05, New East NewYork City,
                            Near rebay resort -1111
                        </li>
                        <li>
                            <div class="item-icon"><i class="far fa-envelope"></i></div>
                            rannarecipes@gmail.com
                        </li>
                        <li>
                            <div class="item-icon"><i class="fas fa-phone"></i></div>
                            +123 5889 000 - 10, +123 8889 011 - 22
                        </li>
                        <li>
                            <div class="item-icon"><i class="fas fa-fax"></i></div>
                            +9856000, +9856010
                        </li>
                    </ul>
                </div>
                <div class="section-heading heading-dark">
                    <h3 class="item-heading-big">Send Us Message</h3>
                </div>
                <form id="contact-form" class="contact-form-box" method="post" action="{% url 'pages:contact' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="text" placeholder="Name *" class="form-control" name="name" data-error="Name field is required"
                                required>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-6 form-group">
                            <input type="email" placeholder="E-mail *" class="form-control" name="email" data-error="E-mail field is required"
                                required>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-12 form-group">
                            <input type="text" placeholder="Subject *" class="form-control" name="subject"
                                data-error="Subject field is required" required>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-12 form-group">
                            <textarea placeholder="Type your text" class="textarea form-control" name="message" id="form-message"
                                rows="7" cols="20" data-error="Message field is required" required></textarea>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-12 form-group mb-0 mt-3">
                            <button type="submit" class="item-btn">SUBMIT MESSAGE</button>
                        </div>
                        <div class="form-response"></div>
                    </div>
                </form>
            </div>
        </div>
        <div class="contact-box-right">
            <div class="google-map-wrap-layout1">
                <iframe src="https://maps.google.com/maps?q=-37.81618%2C%20144.95692&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed"></iframe>
            </div>
        </div>
    </section>
    <!-- Contact Page Area End Here -->
{% endblock %}

{% block extra_js %}
<!-- Custom Js -->
<script src="{% static 'js/main.js' %}"></script>
<!-- Google Map js -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBtmXSwv4YmAKtcZyyad9W7D4AC08z0Rb4"></script>

{% endblock %}